{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-integration-graph-viewer.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - integration-ui.example.com
      secretName: spring-integration-graph-viewer-tls
  rules:
    - host: integration-ui.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-integration-graph-viewer.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
