name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '**/src/**'
      - '**/package.json'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_USERNAME }}/spring-integration-graph-viewer:latest
          ghcr.io/${{ github.repository_owner }}/spring-integration-graph-viewer:latest
